elink-iov-platform-web/src/main/java/com/legaoyi/iov/platform/web/controller/MainViewController.java
package com.legaoyi.iov.platform.web.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;

@Controller
public class MainViewController {

    @GetMapping({"/{page}"})
    public String view(@PathVariable String page) {
        return "/" + page;
    }

    @GetMapping({"/{path}/{page}"})
    public String view(@PathVariable String path, @PathVariable String page) {
        return "/" + path + "/" + page;
    }

}

elink-iov-platform-web/src/main/java/com/legaoyi/iov/platform/web/filter/SecurityServlet.java
package com.legaoyi.iov.platform.web.filter;

import java.io.IOException;

import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.annotation.WebFilter;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang3.StringUtils;

/**
 * @author gaoshengbo
 */
@WebFilter(filterName = "securityServlet", urlPatterns = "*.do")
public class SecurityServlet implements Filter {

    @Override
    public void doFilter(ServletRequest req, ServletResponse resp, FilterChain filter) throws IOException, ServletException {
        HttpServletRequest request = (HttpServletRequest) req;
        HttpServletResponse response = (HttpServletResponse) resp;
        HttpSession session = request.getSession(true);
//        Object user = session.getAttribute("user");// 登录人角色
//        String url = request.getRequestURI();
//        // 判断获取的路径不为空且不是访问登录页面或执行登录操作时跳转
//        if (user == null) {
//            if (StringUtils.isNotEmpty(url) && !(url.endsWith("login.do") || url.endsWith("register.do"))) {
//                //response.sendRedirect(request.getContextPath() + "/login.do");
//                java.io.PrintWriter out = response.getWriter();
//                out.println("<html>");
//                out.println("<script>");
//                out.println("window.open ('" + request.getContextPath() + "/login.do','_top')");
//                out.println("</script>");
//                out.println("</html>");
//                return;
//            }
//        }
//        req.setAttribute("user", user);
        filter.doFilter(req, resp);
    }

    @Override
    public void init(FilterConfig arg0) throws ServletException {

    }
}

elink-iov-platform-web/src/main/java/com/legaoyi/iov/platform/web/rest/BaseController.java
package com.legaoyi.iov.platform.web.rest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.ExceptionHandler;

/**
 * @author gaoshengbo
 */
public class BaseController {

    protected static final Logger logger = LoggerFactory.getLogger(BaseController.class);

    @ExceptionHandler
    public Result exceptionHandler(Exception e) {
        String errorMsg;
        if (e.getCause() != null) {
            errorMsg = e.getCause().getMessage();
        } else {
            errorMsg = e.getLocalizedMessage();
            if (errorMsg == null || "".equals(errorMsg)) {
                errorMsg = e.getMessage();
            }
        }
        logger.error("", e);
        return new Result(Result.RESP_CODE_ERROR, errorMsg, null);
    }
}

elink-iov-platform-web/src/main/java/com/legaoyi/iov/platform/web/rest/GeneralController.java
package com.legaoyi.iov.platform.web.rest;

import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.legaoyi.iov.platform.service.DeviceService;
import com.legaoyi.iov.platform.service.GpsService;

@RestController("generalController")
@RequestMapping(value = "/common", produces = {"application/json"})
public class GeneralController extends BaseController {

    @Autowired
    @Qualifier("deviceService")
    private DeviceService deviceService;

    @Autowired
    @Qualifier("gpsService")
    private GpsService gpsService;

    @RequestMapping(value = {"/gps/last/{simCode}"}, method = {RequestMethod.GET})
    public Result get(@PathVariable String simCode) throws Exception {
        return new Result(gpsService.getLastGpsBySimCode(simCode));
    }
    
    
    @RequestMapping(value = {"/gps/last/all"}, method = {RequestMethod.GET})
    public Result getAll() throws Exception {
        return new Result(gpsService.getLastGps());
    }

    @RequestMapping(value = {"/device"}, method = {RequestMethod.POST})
    public Result post(@RequestBody Map<String, Object> form) throws Exception {
        return new Result(deviceService.save(form));
    }

    @RequestMapping(value = {"/device/{id}"}, method = {RequestMethod.PUT})
    public Result put(@PathVariable String id, @RequestBody Map<String, Object> form) throws Exception {
        return this.patch(id, form);
    }

    @RequestMapping(value = {"/device/{id}"}, method = {RequestMethod.PATCH})
    public Result patch(@PathVariable String id, @RequestBody Map<String, Object> form) throws Exception {
        form.put("id", id);
        return new Result(deviceService.save(form));
    }

    @RequestMapping(value = {"/device/{id}"}, method = {RequestMethod.DELETE})
    public Result delete(@PathVariable String id) throws Exception {
        deviceService.delete(id);
        return new Result();
    }
}

elink-iov-platform-web/src/main/webapp/WEB-INF/jsp/addDevice.jsp
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ include file="/common/header.jsp"%>
<link rel="stylesheet" href="<c:url value='/css/nav.css'/>"/>
<title>新增设备</title>
<style type="text/css">
	.layui-layer-setwin .layui-layer-close2 {
		right: -15px !important;
		top: -15px !important;
	}
</style>
</head>
<body>
<div id="device-info-dlg">
		<form id="device-info-dlg-frm">
		    <div style="height:15px;"></div>
			<div class="message_con">
				<label>设备名称：</label> <input type="text" required placeholder="设备名称" class="form-control"  maxlength="16" id="name" name="name"><span class="must">*</span>
			</div>
			<div class="message_con">
				<label>SIM卡号：</label> <input type="text" required placeholder="SIM卡号" class="form-control"  maxlength="12" id="simCode" name="simCode"><span class="must">*</span>
			</div>
			<div class="message_con">
				<label>鉴权码：</label> <input type="text" required placeholder="鉴权码" class="form-control"  maxlength="7" id="authCode" name="authCode" value="123456"><span class="must">*</span>
			</div>
		</form>
		<div class="message_footer">
			<button type="button" class="bule" onclick="saveDeviceInfo();">保存</button>
			<button type="button" class="orgen" onclick="closeDialog();">取消</button>
		</div>
</div>
<%@ include file="/common/common.jsp"%>
</body>
</html>
<script type="text/javascript">
function saveDeviceInfo(){
	var formId = "device-info-dlg-frm";
	if (!validForm(formId)) {
		return;
	}
	var data = $("#"+formId).serializeObject();
	var url = "/common/device.do";
	ajaxAsyncPost(url, data, function(result){
		if (result.code != 0) {
			showErrorMessage(result.message);
		} else {
			showMessage("新增成功！");
			closeDialog();
		}
	});
}
</script>

elink-iov-platform-web/src/main/webapp/WEB-INF/jsp/error.jsp
<!DOCTYPE html>
<html lang="en">
<body>
Something went wrong: ${status} ${error}
</body>
</html>

elink-iov-platform-web/src/main/webapp/WEB-INF/jsp/map.jsp
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ include file="/common/header.jsp"%>
<title>实时监控</title>
<style type="text/css">
	.layui-layer-setwin .layui-layer-close2 {
		right: -15px !important;
		top: -15px !important;
	}
</style>
</head>
<body>
	<!--内容部分-->
	<div class="con1" id="content-div">
		<div class="map_box" id="map_box"></div>
	</div>
	<%@ include file="/common/common.jsp"%>
	<%@ include file="mapScript.jsp"%>
	<script type="text/javascript" src="<c:url value='/js/mapControl.js?v=20200118'/>"></script>
</body>
</html>

elink-iov-platform-web/src/main/webapp/WEB-INF/jsp/mapScript.jsp
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<script type="text/javascript" src="<c:url value='/js/map/gaodeMap.js?v=20190618'/>"></script>
<script type="text/javascript" src="<c:url value='/js/map/mapUtil.js?v=20190618'/>"></script>
<script type="text/javascript" src="<c:url value='/js/map.js?v=20200116'/>"></script>
<script type="text/javascript" src="<c:url value='/js/map/lngLatConverter.js'/>"></script>

elink-iov-platform-web/src/main/webapp/common/common.jsp
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<script type="text/javascript" src="<c:url value='/js/jquery/jQuery-2.2.0.min.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/jquery/jquery.json-2.2.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/jquery/jquery.validate.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/jquery/jquery.validate.ext.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/bootstrap/js/bootstrap.min.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/bootstrap/js/bootstrap-table.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/bootstrap/js/bootstrap-table-zh-CN.min.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/bootstrap/js/bootstrap-select.min.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/bootstrap/js/bootstrap-datetimepicker.min.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/bootstrap/js/bootstrap-datetimepicker.zh-CN.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/layer-v3.1.1/layer.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/common/jsMap.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/common/localStorage.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/common/cache.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/common/dateFormat.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/common/common.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/common/ajaxUtil.js?v=20200106'/>"></script>
<script type="text/javascript" src="<c:url value='/js/base.js?v=20200103'/>"></script>
<script>
function getContextPath(){
	return  "<%=request.getContextPath()%>"; 
}

function isCacheQuery(){
	return "${param.isCacheQuery}";
}

function getUserAccount(){
	return "${sessionScope.user.userAccount}";
}

function getUserName(){
	return "${sessionScope.user.userName}";
}

function isSuperAdmin(){
	return "${sessionScope.user.userType}" == "1";
}

function getUserEnterpriseId(){
	return "${sessionScope.user.enterpriseId}";
}

document.oncontextmenu = function(){
  return false;
}
</script>

elink-iov-platform-web/src/main/webapp/common/footer.jsp
<%@ page language="java" contentType="text/html; charset=utf-8"
	pageEncoding="utf-8"%>
<footer id="footer">
	<div class="container text-center">
		All rights reserved © 2018 | 广西乐高易网络有限公司 桂ICP备15004128号 | <a
			href="http://www.legaoyi.com/#get-in-touch" target="_blank">联系我们</a>
		| 咨询QQ:78772895
	</div>
</footer>

elink-iov-platform-web/src/main/webapp/common/header.jsp
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<link rel="stylesheet" href="<c:url value='/js/bootstrap/css/bootstrap.min.css'/>" />
<link rel="stylesheet" href="<c:url value='/js/bootstrap/css/bootstrap-table.css'/>" />
<link rel="stylesheet" href="<c:url value='/js/bootstrap/css/bootstrap-select.css'/>" />
<link rel="stylesheet" href="<c:url value='/js/bootstrap/css/bootstrap-datetimepicker.min.css'/>" />
<link rel="stylesheet" href="<c:url value='/css/base.css?v=20190545'/>">